import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import { Text, ThemeIcon } from "@mantine/core";
import { IconBrandTwitter, IconBrandFacebook } from "@tabler/icons";
import { ViewButton } from "../components/view-button";
import { BlogList } from "../components/blog-list";
import { Portfolio, PortfolioList } from "../components/portfolio-list";
import { SimpleHeadlineAndTitleSection } from "../components/simple-headline-and-title-section";
import {
  GitHubRepository,
  GitHubRepositoryList,
} from "../components/github-repository-list";
import { Tweet, TwitterList } from "../components/twitter-list";

const Home: NextPage = () => {
  const pink = "bg-pink-600";
  const blogPosts = [...Array(5)].map((_) => ({
    header: "This is a header",
    description:
      "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint. Velit officia consequat duis enim velit mollit.",
    date: "2022.07.11",
  }));
  const portfolios: Portfolio[] = [...Array(2)].map((_) => ({
    thumbnail: "/portfolio-thumbnail.png",
    title: "sumiren ブログ",
    description:
      "技術ブログをやっています。フルスタックエンジニアの浅く広めの技術発信が中心です。月に4本くらい発信します",
    period: "2022.05 -",
  }));
  const repositories: GitHubRepository[] = [...Array(2)].map((_) => ({
    name: "sumiren/bookapp",
    description:
      "control tsundoku books and manage your life of reading nice books.",
    stars: 30,
    forks: 5,
    techRatio: [
      {
        tech: "TypeScript",
        percentage: 50,
        color: "yellow.5",
      },
      {
        tech: "Ruby on Rails",
        percentage: 40,
        color: "red.5",
      },
      {
        tech: "Other",
        percentage: 10,
        color: "dark.0",
      },
    ],
  }));
  const tweets: Tweet[] = [...Array(3)].map((_) => ({
    avatar: "/avatar.jpeg",
    name: "sumiren_t",
    displayName: "sumiren",
    date: "5月25日",
    content:
      "📣 新サービス「Noway Form」をリリースしました！ <br><br>Noway Formは、Notionのデータベースをもとにフォームを作成できるサービスです。これまでGoogle FormsでやっていたことがNotionだけで完結します✌✨ <br><br>試しに使っていただけると幸いです😊 <br><br><a href='https://www.noway-form.com/ja' style='text-decoration: underline'>https://www.noway-form.com/ja</a>",
  }));

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={pink + " px-4 lg:px-32 py-10 text-white"}>
          <div className="flex justify-center">
            <div className="w-full lg:flex lg:justify-between">
              <div>
                <Text className="text-3xl font-bold">Sumiren Portfolio</Text>
                <Text className="mt-2 text-m font-semibold">
                  sumirenのポートフォリオのためのページです
                </Text>
              </div>
              <div className="mt-10">
                <ThemeIcon variant="filled" className={pink}>
                  <IconBrandTwitter></IconBrandTwitter>
                </ThemeIcon>
                <ThemeIcon variant="filled" className={pink}>
                  <IconBrandFacebook></IconBrandFacebook>
                </ThemeIcon>
              </div>
            </div>
          </div>
        </section>
        <div className="px-4 lg:px-32">
          <div className="my-10">
            <SimpleHeadlineAndTitleSection headline="Blog">
              <BlogList blogPosts={blogPosts} />
              <div className="flex justify-center mt-10">
                <ViewButton text="View All" href="/blog"></ViewButton>
              </div>
            </SimpleHeadlineAndTitleSection>
          </div>

          <div className="mt-20 lg:mt-32">
            <SimpleHeadlineAndTitleSection headline="Portfolio">
              <PortfolioList portfolios={portfolios} />
              <div className="flex justify-center mt-10">
                <ViewButton text="View All" href="/blog"></ViewButton>
              </div>
            </SimpleHeadlineAndTitleSection>
          </div>

          <div className="lg:flex lg:justify-between ">
            <div className="mt-20 lg:mt-32 lg:w-5/12">
              <SimpleHeadlineAndTitleSection headline="GitHub">
                <GitHubRepositoryList repositories={repositories} />
                <div className="flex justify-center mt-14">
                  <ViewButton
                    text="View on GitHub"
                    href="https://github.com/sumiren"
                  ></ViewButton>
                </div>
              </SimpleHeadlineAndTitleSection>
            </div>

            <div className="mt-20 lg:mt-32 lg:w-6/12 ">
              <SimpleHeadlineAndTitleSection headline="Twitter">
                <TwitterList tweets={tweets} />
                <div className="flex justify-center mt-10">
                  <ViewButton text="View on Twitter" href="/blog"></ViewButton>
                </div>
              </SimpleHeadlineAndTitleSection>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = () => {
  console.log("get static props");
  return {
    props: {},
  };
};

export default Home;
